abstract: 'Fast, lightweight YAML loader and dumper'
author: 'Audrey Tang <autrijus@autrijus.org>'
distribution_type: module
generated_by: Module::Install version 0.51
license: perl
name: YAML-Syck
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.003
version: 0.14
