
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.54
distribution_type: module
version: 0.23
name: YAML-Syck
author: Audrey Tang <autrijus@autrijus.org>
license: perl
requires: 
  perl: 5.003
abstract: Fast, lightweight YAML loader and dumper
