abstract: Fast, lightweight YAML loader and dumper
author: Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: YAML-Syck
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.00307
version: 0.64
